const exactMenuImages = new Map([
  ["Chicken Starters::Chicken 65", "/chicken65.jpg"],
  ["Chicken Starters::Chicken Tikka", "/chickentiika.jpg"],
  ["Mini Pack::Chicken 65 Mandi (Serves 1)", "/Chicken65Mandi.webp"],
  ["Mini Pack::Chicken Tikka Mandi (Serves 1)", "/ChickenTikkaMandi.webp"],
  ["Fish Mandi::Broasted Fish Mandi", "/broastedfishmandi.webp"],
  ["Fish Mandi::Fish Fried Mandi", "/fishfrymandi.jpg"],
  ["Fish Mandi::Grilled Fish Mandi [Serves 2]", "/grilledfishmandi.jpg"],
  ["Mix Mandi::Mixed Mandi (serves 4 Persons)", "/mixmandi.jpg"],
  ["Mix Mandi::Mixed Mandi (serves 8 Persons)", "/mixmandi.jpg"],
  ["Mix Mandi::Mutton Raan Mandi", "/muttonraanmandi.jpg"],
  ["Chicken Mandi::Chicken Fry piece Mandi", "/chickenfrypiecemandi.webp"],
  ["Chicken Starters::Broasted Chicken Chefs Special", "/boastedchicken.webp"],
  ["Chicken Starters::Chicken Al-faham", "/chickenalfahm.jpg"],
  ["Chicken Starters::Haryali Chicken", "/hariyalichicken.jpg"],
  ["Chicken Starters::Lahori Chicken Seekh Kebab [4 Pcs]", "/chickenseekkabab.jpg"],
  ["Chicken Starters::Lebanese Cream Chicken", "/lebanescreamchicken.jpg"],
  ["Mutton Starters::Arabian Mutton Chops (5 Pcs)", "/arabicmuttonchops.jpg"],
  ["Mutton Starters::Botti Kebab", "/muttonbotikakab.jpg"],
  ["Mutton Starters::Malai Mutton Chefs Special", "/malaimutton.jpg"],
  ["Mutton Starters::Middle East Mutton Sheek Kebab Chefs Special", "/muttonsheekkababmiddleeast.jpg"],
  ["Mutton Starters::Turkish Botti Kebab", "/turkishbotikabab.jpg"],
  ["Seafood Starters::Apollo Fish", "/apolofish.jpg"],
  ["Seafood Starters::Broasted Fish (4 Pcs)", "/friedfish.jpg"],
  ["Seafood Starters::Crispy Fried Prawns Chefs Special", "/friedpranws.jpg"],
  ["Rotis::Butter Naan", "/butternaan.jpg"],
  ["Rotis::Butter Tandoori Roti", "/buttertandooriroti.jpg"],
  ["Rotis::Garlic Butter Naan", "/garlicbutternaan.jpg"],
  ["Rotis::Rumali Roti", "/rumaliroti.jpg"],
  ["Rotis::Rumali Roti (10 pcs)", "/rumaliroti.jpg"],
  ["Rotis::Tandoori Roti", "/buttertandooriroti.jpg"],
  ["Desserts::Cream Kunafa", "/creamkunafa.jpg"],
  ["Desserts::Qurbani Ka Meetha", "/QubbaniKaMeetha.jpg"],
  ["Extra & Add Ons::Afghani Mutton Rosh", "/afganimuttonrosh.jpg"],
  ["Extra & Add Ons::Chicken Faham (full Bird)", "/chcikenfahmfullbird.jpg"],
  ["Extra & Add Ons::Chicken Faham (half Bird)", "/chickenfahamhalf.jpg"],
  ["Extra & Add Ons::Chicken Fry", "/chickenfry.jpg"],
  ["Extra & Add Ons::Fish Fry", "/fishfry.jpg"],
  ["Extra & Add Ons::Fried Onion", "/friedonions.jpg"],
  ["Extra & Add Ons::Mandi Rice", "/mandirice.jpg"],
  ["Extra & Add Ons::Mayonnaise", "/Mayonnaise.jpg"],
  ["Extra & Add Ons::Mutton Dum Roast", "/muttondhumroast.jpg"],
  ["Extra & Add Ons::Mutton Fry", "/muttonfry.jpg"],
  ["Extra & Add Ons::Mutton Juicy", "/muttonjuicymandi.webp"],
  ["Mojitto & Beverages::Arabic Champagne", "/ArabicChampagne.jpg"],
  ["Mojitto & Beverages::Blackcurrant Mojito", "/BlackcurrantMojito.jpg"],
  ["Mojitto & Beverages::Blue Lagoon Mojito", "/bluelagoonmajito.jpg"],
  ["Haleem::Chicken Haleem", "/chickenhallem.jpg"],
  ["Haleem::Mutton Haleem", "/muttonhaleem.jpg"],
  ["Haleem::Special Haleem", "/speicalhaleem.jpg"],
  ["Haleem::Family Haleem", "/familyhaleem.jpg"],
]);

export const getExactMenuImage = (itemTitle, sectionTitle) =>
  exactMenuImages.get(`${sectionTitle}::${itemTitle}`) ?? null;
